select CNAME from CUSTOMER where CITY='NAGPUR' OR CITY='DELHI';

select CNAME, BNAME from DEPOSIT where AMOUNT>4000 AND ACTNO<105;

select * from BORROW where AMOUNT BETWEEN 3000 AND 8000;

select * from BORROW where NOT BNAME IN('ANDHERI');

select ACTNO, CNAME, AMOUNT from DEPOSIT where BNAME IN ('AJNI','KAROLBAGH','M.G. ROAD') AND ACTNO<104;

select TOP 5 * FROM CUSTOMER; 

select TOP 3 * FROM DEPOSIT where AMOUNT>1000;

select TOP 5 LOANNO, CNAME from BORROW where NOT BNAME IN('ANDHERI');

select DISTINCT CITY from CUSTOMER;

select DISTINCT BNAME from BRANCH;

select * from CUSTOMER
ORDER BY CITY;

select * from DEPOSIT
ORDER BY AMOUNT DESC;