update DEPOSIT
SET AMOUNT='5000' 
where AMOUNT='3000';

update BORROW
SET BNAME='C.G.ROAD'
where CNAME='ANIL';

update DEPOSIT
SET ACTNO=111, AMOUNT=5000
where CNAME='SANDIP';

update BORROW
SET AMOUNT=((AMOUNT/10)+AMOUNT);

update DEPOSIT
SET AMOUNT=5000
where ACTNO BETWEEN 103 AND 107;

update BORROW
SET LOANNO=NULL
where LOANNO=321;

select * from BORROW where AMOUNT=NULL;

