update DEPOSIT
SET ACTNO=111, AMOUNT=5000
where CNAME='SANDIP';

update BORROW
SET AMOUNT=((AMOUNT/10)+AMOUNT);

select * from BORROW;


update DEPOSIT
SET AMOUNT=5000
where ACTNO BETWEEN 103 AND 107;

update BORROW
SET LOANNO=NULL
where LOANNO=321;

select * from BORROW where AMOUNT=NULL;
